filebeat.inputs:
- type: docker
  containers.ids:
  - '*'
  processors:
  - add_kubernetes_metadata:
      in_cluster: true

output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["10.0.8.110:9092"]

  # message topic selection + partitioning
  #topic: '%{[fields.log_topic]}'
  topic: 'nextpay-k8s-payment'
