stages:
  - deploy_tools
  - docker_push
  - release

before_script:
  - export CWD=$PWD
  - export DEPLOY_PATH=/home/gitlab-runner/deploy-tools-v2
  - export CI_COMMIT_TAG=${CI_COMMIT_TAG}

pull_deploy_tools:
  stage: deploy_tools
  script:
    - cd $DEPLOY_PATH
    - git pull
  only:
    - develop
    - tags
    - master
    - staging
  tags:
    - shell-runner

docker_push:
  stage: docker_push
  script:
    - mvn clean install
    - cd $DEPLOY_PATH
    - ./build-java-push.sh $CWD
  tags:
    - shell-runner
  only:
    - develop
    - tags
    - master
    - staging

deploy_dev:
  stage: release
  script:
    - cd $DEPLOY_PATH
    - ./deploy-next-servesion.sh coredevelop $CWD 
  only:
    - develop
  tags:
    - shell-runner

deploy_core_staging:
  stage: release
  script:
    - cd $DEPLOY_PATH
    - ./deploy-next-servesion.sh corestaging $CWD
  only:
    - tags
  tags:
    - shell-runner
  when: manual
    
deploy_core_prod:
  stage: release
  script:
    - cd $DEPLOY_PATH
    - ./deploy-next-servesion.sh production $CWD
  only:
    - tags
  tags:
    - shell-runner
  when: manual