version: '3.2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pvb/:/var/www/html/pvb/
      - ./pvc-vendor:/var/www/html/vendor/
    ports:
      - 8083:80
    env_file: sandbox.env

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
